apiVersion: v1
kind: Service
metadata:
  name: iam-finder-svc
spec:
  type: NodePort
  selector:
    app: iam-finder
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
