name: swagger CI

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'api.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate Swagger UI
      uses: Legion2/swagger-ui-action@v1.1.2
      with:
        output: swagger-ui
        spec-file: api.yaml
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: swagger-ui
